import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";
import TopBar from "@/components/TopBar";
import SideBar from "@/components/SideBar";
import SensorProvider from "@/components/SensorProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="custom-scrollbar" suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-between w-full">
            <SideBar />
            <div className="flex flex-col gap-6 w-[80%]">
              <TopBar />
              <div className="p-6">
                <SensorProvider>
                  {children}
                </SensorProvider>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
